name: iOS-CI

on:
  push:
    branches: [__main__]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Debug (iOS Simulator)
        run: |
          xcodebuild \
            -scheme YourAppScheme \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            build

      - name: Build Release (iOS Simulator)
        run: |
          xcodebuild \
            -scheme YourAppScheme \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            build

      - name: Test (Debug)
        run: |
          xcodebuild \
            -scheme YourAppScheme \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            test

      - name: Upload Release Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: ~/Library/Developer/Xcode/DerivedData/
          
